### ISSUE TITLE
Enhancements for DuckHunter interface

### ISSUE THREAD

**Issue by TheNain38** [offensive-security/nethunter-app#106]
- [x] if you change language while being on the preview tab, it should update the preview
- [x] if it was already converted, and then you launch an attack, then it shouldn't reconvert it
- [x] if you didn't changed anything in the convert tab, then it shouldn't reconvert it if you go to preview tab

**Comment by TheNain38** [comment]
All 3 shouldn't be hard to add, if you add a boolean that tells the app if it needs to reconvert the code.

**Comment by jmingov** [comment]
Tho you said you also program in java...

Done.

**Comment by TheNain38** [comment]
Thank you so much @jmingov! Yes, I also program in Java, I've already done a a big project: a game (it isn't on the net, just on my computer). But I said I won't have the time this week because of school and stuff. Again, thank you!

**Comment by TheNain38** [comment]
Also, I think the convert button should be renamed to 'Attack'
