### ISSUE TITLE
Add missing commands in DuckHunter

### ISSUE THREAD

**Issue by TheNain38** [offensive-security/nethunter-app#107]
- [x] REPEAT
- [x] DEFAULT_DELAY
- [x] WIN10CMD ?
- [x] Other commands ?

**Comment by jmingov** [comment]
Well done. :dango:

**Comment by binkybear** [comment]
Yes, great job!

**Comment by TheNain38** [comment]
Thanks, this issue was just here as a reminder, now, duckhunter have another look with all these enhancements ;) Now, I just need to finish the tasks in #106, if you could help me with that ^^ I will thank you... School is here, and I won't be able to do that much code ^^

**Comment by TheNain38** [comment]
Also, maybe you should update the wiki, the last link in the home page of kali-nethunter repo gives a 404 error and also in bullet 7.0 it is written 'Andropid'. Also, the nethunter-app wiki should include something about DuckHunter

**Comment by binkybear** [comment]
The wiki's will be updated this week as there will probably be a release *very soon*.  The nethunter-app wiki will probably be removed and we will focus our efforts in kali-nethunter.

In the meantime we will be not adding any big features this week but mainly looking to clean up any bugs.

**Comment by TheNain38** [comment]
Ah, ok, this is good news to have a new release. My enhancements for DuckHunter corrected bugs too. (And added features). The issues in the GUI just really bother me, I don't find the fact you have to wait 2 secondes before it launches the attack to be really convenient. I will try to correct these before 3.0 arrives!!
