### ISSUE TITLE
BadUsb Issue

### ISSUE THREAD

**Issue by dukenukem2d** [offensive-security/nethunter-app#112]
Hi,

I just installed NetHunter on my Nexus 5 - 5.1.1. and try to use BadUsb MITM Attack. But nothing happen. badusb.log is showing follow message
"tmp-mksh:<stdin>[1]:start-badusb-lollipop: not found
I tried to run this command
su
/sdcard/files/startbadusb-lollipop.sh

I got this one

tmp-mksh: /sdcard/files/startbadusb-lollipop.sh: can't execute: Permission denied

What's mean? How to fix?

Thanks.

**Comment by jmingov** [comment]
Hi
How did you installed nethunter?

Which instructions you followed?

I a stock rom the one you used as base?

**Comment by dukenukem2d** [comment]
Hi,

Stock ROM 5.1.1. rooted, twrp, busybox, Nethunter ROM.

**Comment by jmingov** [comment]
You used a zip from https://www.offensive-security.com/kali-linux-nethunter-download/?

**Comment by dukenukem2d** [comment]
yes.

**Comment by jmingov** [comment]
Well, is an old version, no fixes will be applied there. The images will be updated soon.

The fix is installing the latest nethunter from the main repo, you need to build it:

https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter

**Comment by dukenukem2d** [comment]
Noted. 

Thanks a lot.
