### ISSUE TITLE
android app's default stored command  looks for /usr/bin/dumpmifare instead of /usr/bin/dumpmifare.sh

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/nethunter-app#118]
Currently the nethunter-utils package installs the dumpmifare script to /usr/bin/dumpmifare.sh but the nethunter app in it's stored command app looks for this script under the name /usr/bin/dumpmifare (sans extension) a work around is to make a symlink between the two but either the nethunter-utils package or the default stored command in the android app should be synced with the appropriate file name.

**Comment by jmingov** [comment]
Duplicate and solved.

https://github.com/offensive-security/kali-nethunter/issues/347
