### ISSUE TITLE
error launching intent install android terminal

### ISSUE THREAD

**Issue by 0o0TheDude0o0** [offensive-security/nethunter-app#124]
I get this error when trying to launch vnc server or any other actions that require terminal. I am using terminal emulator for Android from the play store... Any thoughts?

**Comment by binkybear** [comment]
You should be using terminal emulator associated with nethunter app which supports those custom intents.  They apps can be downloaded here:

https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer/update/data/app.  Just get the raw file and install with adb or manually.
