### ISSUE TITLE
nethunter > wifite

### ISSUE THREAD

**Issue by harayz** [offensive-security/nethunter-app#126]
i am running nethunter on nexus 7 2012 3G (nakasig/tilapia) with custom rom (CM12.1) and kernel.
wifite could not find the wlan1 connected via usb. when i run the terminal via nethunter app, lsusb list the device as follows:
`148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter`

however ifconfig and iwconfig does not show the connected device. ive tried several several different devices and other usb cables including externally powered ones. ive even tried different kernel but below is the current one that i am using now:
`Linux version 3.1.10-oxydo-revamp#3+ (sgtmeow@sgtmeow-pc) (gcc version 4.9.4 20150715 (prerelease) (UBERTC-4.9.4) ) #5 SMP PREEMPT Thu Jul 16 22:34:53 BDT 2015`

can someone please help me out - what am i missing here?

**Comment by binkybear** [comment]
The kernel you are running may now support the rt* adapter or its possible you are missing firmware.  Maybe try this kernel instead:

https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/kernel-only/kernel-nethunter-flocm-lollipop-3.0.5-20160410-1617.zip
