### ISSUE TITLE
[suggestion] hostapd-wpe front end

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/nethunter-app#128]
So often times on a pen test Mana is less useful as a targeted evil twin attack (we only care about impersonating one network) and we often only need to capture WPA-enterprise credentials, usually that means using hostapd-wpe. Would it be possible to add hostapd-wpe to the Nethunter repository and add to the nethunter app a front end to hostapd-wpe (GUI based config and tail of hostapd-wpe's credential log)?

**Comment by binkybear** [comment]
I looked into this and it seems pretty doable.  Here is the install script I used for testing:
```bash
cd /tmp
git clone https://github.com/OpenSecurityResearch/hostapd-wpe
wget http://w1.fi/releases/hostapd-2.2.tar.gz
tar -zxf hostapd-2.2.tar.gz
cd hostapd-2.2
patch -p1 < ../hostapd-wpe/hostapd-wpe.patch 
cd hostapd
sed -i 's/#CONFIG_LIBNL32=y/CONFIG_LIBNL32=y/g' .config
make
chmod 755 hostapd-wpe
cp hostapd-wpe /usr/bin/hostapd-wpe
cp hostapd-wpe.eap_user /usr/share/hostapd-wpe/hostapd-wpe.eap_user
cd /tmp/hostapd-wpe/
mkdir -p /usr/share/hostapd-wpe/certs
cp -rf certs /usr/share/hostapd-wpe
chmod 755 /usr/share/hostapd-wpe/certs/bootstrap
#cd /usr/share/hostapd-wpe/certs/
#./bootstrap
```
The configuration file I moved to Nethunter application configuration files and pointed it to the certificates and user file to where we copied it.

Adding the above to the chroot build would be easy (just copy and paste).  The Nethunter app changes shouldn't be terribly difficult either since it uses nearly the same file as hostapd-mana.  Just needs some slight changes to regex/ui.

I think the biggest challenge would be making sure the certificates get generated by bootstrap along with how to run it smoothly.

**Comment by thesle3p** [comment]
Nice, any idea how soon this could be implemented?

**Comment by binkybear** [comment]
OK - so maybe you can help with testing.  Install hostapd-wpe using instructions above.  Then install apk:

https://transfer.sh/pDNCa/nethunter-app-release.apk

Under mana-toolkit you can modify hostapd-wpe in the second tab and generate certificates.  When you are ready, hit "start mana" and select hostapd-wpe.  Let me know what needs to be fixed/added.

**Comment by thesle3p** [comment]
Will check that out in a bit, just signed on to work.

-----Original Message-----

**Comment by thesle3p** [comment]
Ok, so two things first  to compile hostapd-wpe needs two dependencies  that you missed

```sudo apt-get install libnl-3-dev``` 
and
```sudo apt-get install libnl-genl-3-dev```

Also when I try and connect to the honey-net hostapd-wpe seems to want a EAP type different then what ever eap type I specify in the config, a example below:

```
Configuration file: /sdcard/nh_files/configs/hostapd-wpe.conf
Using interface wlan1 with hwaddr 00:11:22:33:44:00 and ssid "Free_Internet"
wlan1: interface state UNINITIALIZED->ENABLED
wlan1: AP-ENABLED 
wlan1: STA  <redacted> IEEE 802.11: authenticated
wlan1: STA  <redacted>  IEEE 802.11: associated (aid 1)
wlan1: CTRL-EVENT-EAP-STARTED <redacted> 
wlan1: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
wlan1: CTRL-EVENT-EAP-FAILURE <redacted> 
wlan1: STA <redacted> IEEE 802.1X: authentication failed - EAP type: 0 ((null))
wlan1: STA <redacted>  IEEE 802.1X: Supplicant used different EAP type: 1 (Identity)
wlan1: STA <redacted>  IEEE 802.11: deauthenticated due to local deauth request
```

I never saw this error on x86 Kali or stock debian, not sure what's going on there.

**Comment by binkybear** [comment]
Thanks for testing.  You can get better debugging results with a -dd.  So the command to run would be:
```bash
ifconfig wlan1 up && /usr/bin/hostapd-wpe -dd /sdcard/nh_files/configs/hostapd-wpe.conf
```
Or if you just want a new apk with -dd built it:
https://transfer.sh/VxxYP/nethunter-app-release.apk

**Comment by binkybear** [comment]
I think everything is working now:

https://transfer.sh/YJHkL/nethunter-app-release.apk

I've also used the patch for 2.5 hostapd instead.  I've submitted a pull request with the updated binary and cert files: https://github.com/offensive-security/nethunter-utils/pull/15

Eventually you should only need to run an apt-get update/upgrade and install latest apk.  I took a screenshot to confirm it worked in link below:

Tested on OnePlus1 using TL-WN722N:

[Screenshot](http://i.imgur.com/BkrjAjd.png)

**Comment by thesle3p** [comment]
That  version bricks the HID attack menu in the app and makes
nethunter/android no longer see wlan1.

**Comment by binkybear** [comment]
Are you sure the kernel didn't get updated?  There were no changes to hid and theres no possible way the app removed ability to detect wlan1. (Feel free to check git history)

**Comment by thesle3p** [comment]
When i go to the HID attack menu the app crashes. I was able to fix the
wlan1 detection issue with a reboot.

**Comment by binkybear** [comment]
Ah I see now on the hid app crash.  Will look for problem/fix and upload.  Thanks for the good eye!

**Comment by thesle3p** [comment]
Now that I fixed the wlan1 detection issue I will try the host apd issue

**Comment by thesle3p** [comment]
Tried using the apk you sent and hostapd-wpe 2.5 with the patch from the repo you used with the same authentication problem.

**Comment by binkybear** [comment]
Fixed HID error:
https://github.com/offensive-security/nethunter-app/commit/9ba279845b756576efbcbce1b657ed403f6dda43

New APK with HID fix:
https://transfer.sh/IJod2/nethunter-app-release.apk

The crash is occurring I believe because of some changes in Android API.

--------
So back to your authentication issue, I assume its exactly same error as before?  Did you also try "forgetting" network then joining?  Just trying to rule out what could be causing issue.

**Comment by thesle3p** [comment]
I tried that. I also tried from both android and Debian.

**Comment by binkybear** [comment]
Did you try off the 2.5 hostapd?  Here is the binary I used (which worked for me):

https://github.com/binkybear/nethunter-utils/blob/master/usr/bin/hostapd-wpe

(I used TPLINK in testing)

**Comment by thesle3p** [comment]
Ok, so that binary seems to require different libssl binaries  then apt-get install provides and the app crash bug is present in the kali services and duck hunter tabs as well.

**Comment by binkybear** [comment]
Reverted API back to earlier appears to fix issues with app crashes.  However, we will one day have to upgrade to latest api and will probably encounter these issues again:

https://transfer.sh/4EvQ7/nethunter-app-release.apk

**Comment by thesle3p** [comment]
Great, but so far I have been unable to get hostapd-wpe to capture creds, once hostapd-wpe is pushed to the nethunter repo I will try again. Also just a suggestion maybe the app should parse hostapd-wpe's output and log captured creds to a file? 

-----Original Message-----

**Comment by thesle3p** [comment]
Any idea when hostapd-wpe will be pushed to the Nethunter Repo?

**Comment by thesle3p** [comment]
Flashing nethunter again and compiling hostapd-wpe worked, only suggestion is to have the app parse hostapd-wpe's log file and save it's contents to a external file to make offline cracking easier.

**Comment by Lexus89** [comment]
First of all sorry for replying to this closed feature request. 

I was wondering why switching to hostapd-wpe if you can also set hostapd-mana to target a single AP (enable_mana=1 - means shutting down KARMA)? Wouldn't it be easier just having a single hostapd installation on nethunter? Mana has been patched as well for the nt_domain_hack (patch still pending approval at hostapd-wpe repo).

https://github.com/OpenSecurityResearch/hostapd-wpe/pull/4

Also had trouble writing captures passwords/hashes to the log file with hostapd-wpe. 

Some suggestions for nethunter would be adding a log file and karma enabled/disabled option at the nethunter gui and also configurable EAP type(s). The latter could be useful if you want to perform dumb-down attacks. In Freeradius you can set PEAP, "preferred_eap_type" to GTC and configure GTC for PAP.

https://www.dinosec.com/docs/Vulnerabilidades_Wi-Fi_moviles_UCLM-2014_RaulSiles-DinoSec_v1.0.pdf
