### ISSUE TITLE
attempting to compile the nethunter app from android studio always make it crash

### ISSUE THREAD

**Issue by qwertyIsMyPassword** [offensive-security/nethunter-app#146]
If you attempt to generate your own nethuneter app from android studio, you get  an error after apk install from the phone - "no title" terminals or "nethunter has stopped working. "

**Comment by binkybear** [comment]
You need to give a bit more information.  I just generated a pushed an apk a minute ago and everything is working fine.

Do you have a logcat with error?  What OS are you on?

**Comment by qwertyIsMyPassword** [comment]
I'm on cm 13, compiling the android project from with windows. The apk is install, but my attempt to launch for ex - the Kali service tab result in app crash. Please try it and let me know if you can replicate it. Else I will provide logcat. 

I am sorry about my English. It is not my first language.

**Comment by binkybear** [comment]
I see error now.  Just that tab right or do you see it anywhere else?

**Comment by binkybear** [comment]
Please try pulling with latest update and see if it's fixed for you.

**Comment by qwertyIsMyPassword** [comment]
Thank you for the help. I also have noticed it is crash when I try to run any script needing root access .  example - try to add new netapackages create crash, try to run nethunter scripts cause crash, hid attack is not run after app update (or my custom compile on android studio) etc. basically all section of app that need root access are fail. please check. 

thank you.

**Comment by binkybear** [comment]
I can't recreate this.  Running update and metapackages runs fine for me as well as other custom commands.

Hid attack is running fine for me also.  Maybe try doing a clean and rebuild? Also, double check permissions for nethunter app and terminal app.  If you can also check logcat (Android Monitor in Android Studio) that may give an indication of error you are getting.
