### ISSUE TITLE
Nethunter App does not have permission to send to NetHunter erminal! & "error launching intent. install android terminal"

### ISSUE THREAD

**Issue by Sitsme** [offensive-security/nethunter-app#167]
Help..
i was installed nethunter Version 3.15.4(release-keys) app on my Oppo R815 (App,Chroot, ..etc)
I already remove Chroot, Reinstall Busybox, Reinstall nethunter and all tutorial on Google

and i cant found my values on /res/value<==nothing on res
my android phone spesification and my nethunter : 
-oppo r815 os 4.2.1
-Linux version 3.4.5 (root@ubuntu)
-Busybox v1.26.2 -streicson
-Nethunter Terminal is Not Installed
-lo inet 127.0.0.1/8
-ccmni0 inet 10.56.133.14/8

and its full install and complete the installation.

**Comment by Cubuss** [comment]
https://github.com/offensive-security/kali-nethunter/issues/346

**Comment by Re4son** [comment]
Fixed in 2019.1
