### ISSUE TITLE
Wardriving and Deauth issues

### ISSUE THREAD

**Issue by Bry-fi** [offensive-security/nethunter-app#176]
Wardriving does not work. In previous version the wardriving feature would activate the notification in the top right. I am using a Nexus 6 lollipop. I fixed this by using a previous version of the app to anyone having this issue. The deauth just crashes when you scan for networks.

**Comment by sk-y2k** [comment]
+1
Agreed. Didn't test wardrobing, but Deauth crashing...

**Comment by nik012003** [comment]
I think I've found the bug in the Deauth fragment and I'll fix it as soon possibile.
Could you send me a logcat, just to be sure I'm facing the same bug as you.

**Comment by Re4son** [comment]
Fixed in version 2019.1
