### ISSUE TITLE
Not allowed to start service Intent

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/nethunter-app#178]
Hi, @binkybear 

I found that the latest nethunter-app has some issues which not allowing the app running in background.

Some references [here](https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten)

Would you help to fix it? Thank you.

**Comment by aeroroland** [comment]
I think this is may be due to the runOnBoot permissions changing for Android O, but it would be helpful if you could add what you were doing when you got the error message. I'll submit a pull request with my fixes.

**Comment by Re4son** [comment]
Should be working again with nethunter-app >= 2019.1
