### ISSUE TITLE
Certificate pinning change yet

### ISSUE THREAD

**Issue by venssy** [offensive-security/nethunter-app#179]
https://github.com/offensive-security/nethunter-app/blob/0855cdb6b22d604e707fc8b005a8ad090120d604/src/com/offsec/nethunter/ChrootManagerFragment.java#L125
Pin changed to b7dcaa15ba91e250fb58c30658ca9817c668a2d6.

**Comment by Re4son** [comment]
Thanks for letting us know.
Fixed in 11b49dc38a92c59142456a9a274c92009d35d253
