### ISSUE TITLE
Occasional odd behavior from app

### ISSUE THREAD

**Issue by palmerit** [offensive-security/nethunter-app#18]
I haven't narrowed this down yet,  but I'm opening the issue anyway. Hoping you guys can give me a hint or have me test something to help narrow this down.

"occasionally" when I reboot my phone with the external antenna plugged into an OTG cable, the nethunter app will appear as it does in the below screenshot.  *when* this issue manifests, it seems like every subsequent launch of the app will behave the same way, including after a fresh reboot.  UNTIL I reboot the device without the external wifi adapter plugged in.  Then it appears to work fine until the next "random" (I use the word, even though I know it's not random, it's just hard to reproduce) time it occurs.

This is using the latest [Kali-Nethunter](https://github.com/offensive-security/kali-nethunter/commit/af9a9052134f0e9a8a1cce0920cf6125db6c0b80) build taken from the top of the 'development' branch.  The device is a OnePlus One (bacon) running stock firmware 4.4.4

![screenshot_2014-12-29-23-51-47](https://cloud.githubusercontent.com/assets/803978/5575880/a00464ae-8fb9-11e4-874b-9a6a35e6582a.png)

**Comment by binkybear** [comment]
Solved.
