### ISSUE TITLE
SearchSploit and CustomCommands causes the app crash

### ISSUE THREAD

**Issue by flypatriot** [offensive-security/nethunter-app#188]
OnePlus 3T (A3003) Nougat 7.1.1 (OxygenOS 4.5.1). Last NetHunter nightly build 2017.11-18-1618 and ZaneZam boeffla-nethunter kernel v.2.2_20171124.
Compiling platform - last Android Studio (Build Tools - 28.0.2, SDK Tools - 26.1.1, SDK Platform-Tools - 28.0.1, gradle - 4.10, gradle build tool - 3.3.0-alpha08).
The app compiles without any problems. Everything's fine. While runniing in mobile there are few crashes at first start but then it's ok except choosing "custom commands" and "searchsploit" in menu app which always closes app without any errors. I've tried to recompile the app many times but it didn't help.
Really stuck there...
P.S. Sorry for my english.

**Comment by flypatriot** [comment]
After debugging find a problem in **androidx.appcompat.widget.SearchView**. To solve this problem you need to add **line import android.widget.SearchView;** in import section of two files: SearchSploitFragment.java and CustomCommandsFragment.java. Don't forget to delete or comment in line **import androidx.appcompat.widget.SearchView;**

**Comment by kimocoder** [comment]
@fat-tire
