### ISSUE TITLE
Adding Macchanger & Monitor mode to the app [ONGOING]

### ISSUE THREAD

**Issue by jmingov** [offensive-security/nethunter-app#19]
Just a couple of handy features.

**Comment by Zaxscdvf** [comment]
hmm.. would be convenient but pretty easy to do it yourself.

**Comment by binkybear** [comment]
I think it would be a great addition to app.

**Comment by TheNain38** [comment]
+1

**Comment by jmingov** [comment]
This is in the latest app already.
