### ISSUE TITLE
chroot download/install fails [Android 9]

### ISSUE THREAD

**Issue by kimocoder** [offensive-security/nethunter-app#193]
The chroot download/install fails with the message that there is "no network connection" which isn't correct.. unpacking to "/data/local/nhsystem" is a fix for it I used, but I'd would been nice to have it fixed.

Thanks

**Comment by Re4son** [comment]
I'll look into it

**Comment by Re4son** [comment]
Which arch?

**Comment by kimocoder** [comment]
arm64. Think I got it, testing/building the debug apk now

**Comment by full10** [comment]
What is the target path for chroot?

**Comment by kimocoder** [comment]
/data/local/nhsystem

Bur I've fixed it in those commits

**Comment by full10** [comment]
Ok trying it now. Ty
