### ISSUE TITLE
App crashes seemingly randomly when starting it

### ISSUE THREAD

**Issue by unknownpwn** [offensive-security/nethunter-app#21]
Sometimes when the app is started, it crashes. Seems to happen if you've started the app, then go about with your business in other apps and then click the shortcut again. But I'm not 100% sure on if that is the case or if it is "random". Here's the output from CatLog.

![img_20150108_173736](https://cloud.githubusercontent.com/assets/9800002/5669131/77fbe9a0-9775-11e4-820c-962238f3137a.jpg)
![001](https://cloud.githubusercontent.com/assets/9800002/5669130/7349c03a-9775-11e4-9d8a-c4fd0e23e38d.jpg)

**Comment by jmingov** [comment]
Long time i dont see a fc ^^ . This can be closed @binkybear
