### ISSUE TITLE
Persistance in settings under HID attack

### ISSUE THREAD

**Issue by unknownpwn** [offensive-security/nethunter-app#22]
If I choose, from the menu, UAC Bypass Windows 7 and Language Spanish, click update, then switch tabs to another (say for example Nethunter Home) and then back again, the settings I chose from the menu are reset back to normal (No UAC bypass and English).

Is it possible to retain these settings while switching tabs?

**Comment by jmingov** [comment]
Yes, it is posible, storing the instance state and restoring it again(from saved instance), but for a 'permanent chage' we should store an read the options from the SharedPreferences for example.

Im really bussy these week. I can take a look in a few days if isnt solved.

@pawco

**Comment by pawco** [comment]
I'm already working on that. As soon as I finish I'll post update here.

**Comment by unknownpwn** [comment]
Awesome, thanks @pawco @jmingov

**Comment by pawco** [comment]
This is fixed. App will retain UAC Bypass and Keyboard layout settings not only when switching tabs, but also if phone is restarted.

**Comment by unknownpwn** [comment]
Fantastic, thank you @pawco
