### ISSUE TITLE
Please, Safety first

### ISSUE THREAD

**Issue by discipuloosho** [offensive-security/nethunter-app#24]
I know that is error set policy selinux permissive from startup. (Sorry my poor English) So, I think it is more convenient, activate it when necessary, that is, when we start the nethunter app. Here is my contribution:

// Set SELinux to permissive
private static final String COMMAND = "su 0 setenforce 0"; 
try {
  Runtime.getRuntime().exec(COMMAND);
} catch (IOException e) {
  e.printStackTrace();
}

and equal but contrary when close nethunter app. I spoke with binkybear about setenforce in bootkali and killkali files, i think in app is more efficient.
Thanks

**Comment by jmingov** [comment]
Hi, as far i know right now, the set enforce changes are handled by the nethunter script (bootkali) and not by the app. (https://github.com/offensive-security/kali-nethunter/blob/master/flash/system/bin/bootkali#L2)

We launch the processes from the app in the format su -c bootkali [commands].

If we remove the setenforce from the bootkali script, we can have troubles launching programs straight from the console?

**Comment by binkybear** [comment]
I think it makes more sense to have it in bootkali for now.  Having it in the app means it will automatically set to permissive before we even use the chroot.  Although, I don't think either change is necessarily "bad."  I'm just not sure adding it to the app is needed at the moment.  Let me know if you feel otherwise @discipuloosho.

**Comment by discipuloosho** [comment]
For example, hid keyboard attack doesn't work if selinux is enforcement, but hid attack doesn't need execute boootkali file. I think that nethunter app is the control center nethunter, so the app must open and close necesary global permissions. But is my suggestion.

**Comment by binkybear** [comment]
@discipuloosho - It actually launches through bootkali now:

https://github.com/offensive-security/kali-nethunter/blob/master/flash/system/bin/bootkali#L182

We have merged the latest changes from development back to master on the nethunter repo also since there was a recent release.
