### ISSUE TITLE
source for nethunter-app does not build.

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/nethunter-app#26]
Hi I am a android newb so I don't know if the nethunter app is bugged or if I just failed at compiling it but when I try and build the nethunter-app from source I get this error message:
aapt package -M ./AndroidManifest.xml 
./AndroidManifest.xml:2: error: No resource identifier found for attribute 'versionCode' in package 'android'

./AndroidManifest.xml:2: error: No resource identifier found for attribute 'versionName' in package 'android'

./AndroidManifest.xml:8: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:9: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:10: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:11: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:13: error: No resource identifier found for attribute 'minSdkVersion' in package 'android'

./AndroidManifest.xml:13: error: No resource identifier found for attribute 'targetSdkVersion' in package 'android'

./AndroidManifest.xml:17: error: No resource identifier found for attribute 'allowBackup' in package 'android'

./AndroidManifest.xml:17: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:17: error: No resource identifier found for attribute 'icon' in package 'android'

./AndroidManifest.xml:17: error: No resource identifier found for attribute 'theme' in package 'android'

./AndroidManifest.xml:23: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:23: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:23: error: No resource identifier found for attribute 'configChanges' in package 'android'

./AndroidManifest.xml:27: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:28: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:30: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:31: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:36: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:36: error: No resource identifier found for attribute 'targetActivity' in package 'android'

./AndroidManifest.xml:36: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:41: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:42: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:44: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:44: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:49: error: No resource identifier found for attribute 'targetActivity' in package 'android'

./AndroidManifest.xml:49: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:49: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:54: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:55: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:57: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:57: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:62: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:62: error: No resource identifier found for attribute 'targetActivity' in package 'android'

./AndroidManifest.xml:62: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:67: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:68: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:70: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:70: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:75: error: No resource identifier found for attribute 'targetActivity' in package 'android'

./AndroidManifest.xml:75: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:75: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:75: error: No resource identifier found for attribute 'windowSoftInputMode' in package 'android'

./AndroidManifest.xml:81: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:82: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:84: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:84: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:88: error: No resource identifier found for attribute 'targetActivity' in package 'android'

./AndroidManifest.xml:88: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:88: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:88: error: No resource identifier found for attribute 'windowSoftInputMode' in package 'android'

./AndroidManifest.xml:94: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:95: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:97: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:97: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:101: error: No resource identifier found for attribute 'targetActivity' in package 'android'

./AndroidManifest.xml:101: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:101: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:101: error: No resource identifier found for attribute 'windowSoftInputMode' in package 'android'

./AndroidManifest.xml:107: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:108: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:110: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:110: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:129: error: No resource identifier found for attribute 'targetActivity' in package 'android'

./AndroidManifest.xml:129: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:129: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:129: error: No resource identifier found for attribute 'windowSoftInputMode' in package 'android'

./AndroidManifest.xml:135: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:136: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:138: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:138: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:143: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:143: error: No resource identifier found for attribute 'windowSoftInputMode' in package 'android'

./AndroidManifest.xml:143: error: No resource identifier found for attribute 'label' in package 'android'

./AndroidManifest.xml:147: error: No resource identifier found for attribute 'name' in package 'android'

./AndroidManifest.xml:147: error: No resource identifier found for attribute 'value' in package 'android'

./AndroidManifest.xml:17: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').

./AndroidManifest.xml:17: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/ic_launcher').

./AndroidManifest.xml:17: error: Error: No resource found that matches the given name (at 'theme' with value '@style/AppTheme').

./AndroidManifest.xml:23: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').

./AndroidManifest.xml:27: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_nav_home_label').

./AndroidManifest.xml:36: error: Error: No resource found that matches the given name (at 'label' with value '@string/KaliLauncherLabel').

./AndroidManifest.xml:49: error: Error: No resource found that matches the given name (at 'label' with value '@string/kali_services_label').

./AndroidManifest.xml:62: error: Error: No resource found that matches the given name (at 'label' with value '@string/hid_label').

./AndroidManifest.xml:75: error: Error: No resource found that matches the given name (at 'label' with value '@string/badusb_label').

./AndroidManifest.xml:88: error: Error: No resource found that matches the given name (at 'label' with value '@string/mana_label').

./AndroidManifest.xml:101: error: Error: No resource found that matches the given name (at 'label' with value '@string/dnsmasq_label').

./AndroidManifest.xml:129: error: Error: No resource found that matches the given name (at 'label' with value '@string/iptables_label').

**Comment by jmingov** [comment]
Hey @thesle3p lets debug this.

Which IDE are you using? (Eclipse o Andrpid Studio?)

Something looks miss configured in the IDE, since @pawco made a build a few hours ago with your pull request.

**Comment by thesle3p** [comment]
I am using Android studio and now I can get the app to compile and
install via ADB but when I run it (on a nexus 7 2013 wifi-only) the app
crashes and I get the error "Unfortunately,NetHunter Android has
stopped"

**Comment by pawco** [comment]
Is there any log?

**Comment by thesle3p** [comment]
From Android? There isn't a stack trace on the error message if that's
what you mean. However when I make/build the nethunter app I get these
warnings from Android-studio:
Information:Using javac 1.7.0_75 to compile java sources
Information:Android Resource Caching: Caching resources [nethunter-app]
Information:Android Resource Caching: [nethunter-app] Crunching PNG
Files in source dir: nethunter-app/res
Information:Android Resource Caching: [nethunter-app] To destination
dir: .AndroidStudio/system/compile-server/nethunter-app_ed68dfdf/android/res_cache/nethunter-app
Information:Compilation completed successfully with 6 warnings in 6 sec
Information:0 errors
Information:6 warnings
Warning:Android Resource Caching: [nethunter-app]
nethunter-app/res/drawable-hdpi/ic_drawer.png: libpng warning: iCCP: Not
recognizing known sRGB profile that has been edited
Warning:Android Resource Caching:
[nethunter-app]nethunter-app/res/drawable-hdpi/offsec.png: libpng
warning: iCCP: Not recognizing known sRGB profile that has been edited
Warning:Android Resource Caching:
[nethunter-app]nethunter-app/res/drawable-ldpi/offsec.png: libpng
warning: iCCP: Not recognizing known sRGB profile that has been edited
Warning:Android Resource Caching: [nethunter-app]
nethunter-app/res/drawable-mdpi/ic_drawer.png: libpng warning: iCCP: Not
recognizing known sRGB profile that has been edited
Warning:Android Resource Caching:  
[nethunter-app] nethunter-app/res/drawable-mdpi/offsec.png: libpng
warning: iCCP: Not recognizing known sRGB profile that has been edited
Warning:Android Resource Caching: [nethunter-app]
nethunter-app/res/drawable-xhdpi/ic_drawer.png: libpng warning: iCCP:
Not recognizing known sRGB profile that has been edited

**Comment by pawco** [comment]
I'm not using Android studio, so maybe I'm wrong but when I google for your problem looks like a problem in libpng.

```These are just warnings because the newer libpng we built against is stricter about the color profile. We will fix this in an upcoming release, but this shouldn't be an issue.```
But, even with that warnings, you should be able to build the app.

What build tools version you are using? Maybe to try to downgrade?

PS Again, all this is my conclusion after googling the problem, I don't have android studio installed to be able to debug.

**Comment by thesle3p** [comment]
I now can get the nethunter-app to build but whenever  I open it I get a
error message and when I check logcat I get this:
E/AndroidRuntime(26641): Caused by: java.lang.ClassNotFoundException:
Didn't find class "com.offsec.nethunter.AppNavHomeActivity" on path:
DexPathList[[zip file
"/data/app/com.offsec.nethunter-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.offsec.nethunter-1, /vendor/lib, /system/lib]]

**Comment by fat-tire** [comment]
I just posted a [pull request](https://github.com/offensive-security/nethunter-app/pull/30) that includes a build.gradle file that may help if you're building in Android Studio.  Hope it helps.

**Comment by binkybear** [comment]
Builds fine, closing issue.
