### ISSUE TITLE
Needs a LICENSE

### ISSUE THREAD

**Issue by fat-tire** [offensive-security/nethunter-app#29]
Talked w/binkybear- wasn't sure what the license was...  I vote for GPLv3 but anyhoo...

**Comment by jmingov** [comment]
Here is  the Kali Linux Open Source Policy (standar distribution only?) 

http://docs.kali.org/kali-policy/kali-linux-open-source-policy

Althought @offensive-security probably will point the right license to use.

**Comment by Zaxscdvf** [comment]
http://stopnerds.org/license/ vote this

**Comment by binkybear** [comment]
License added.
