### ISSUE TITLE
Didnt get iptables in sidemenu

### ISSUE THREAD

**Issue by royalhacker** [offensive-security/nethunter-app#39]
hello @binkybear 
i hv been having a strange issue. 
i compiled the app on my pc and even then i didnt see the new iptables side menu item.
i digged a little and got a array that seemed suspicious in sideview.java

  public String[][] querySampleActivities() {
        Intent intent = new Intent(Intent.ACTION_MAIN, null);
        intent.setPackage(getActivity().getPackageName());
        intent.addCategory(Intent.CATEGORY_SAMPLE_CODE);

        PackageManager pm = getActivity().getPackageManager();
        List<ResolveInfo> infos = pm.queryIntentActivities(intent, 0);

        final int count = infos.size();
        int total = count;
        if (Build.VERSION.SDK_INT >= 21) {
        	total = count-1;
        }
        String[] activityNames = new String[total];
        String[] activityActions = new String[total];
        for (int i = 0; i < count; i++) {
            final ResolveInfo info = infos.get(i);
            final CharSequence labelSeq = info.loadLabel(pm);
            if (!labelSeq.toString().equals("Iptables Configuration") || Build.VERSION.SDK_INT < 21) {
            	String label = labelSeq != null ? labelSeq.toString() : info.activityInfo.name;
            	activityNames[i] = label;
                activityActions[i] = info.activityInfo.name;
            }
        }
        return new String[][]{activityNames, activityActions};
    }

could you please explain the cause of the problem . 
it will help me if u would explain the mechanism of listview .

**Comment by jmingov** [comment]
Hey there, this lines

    if (Build.VERSION.SDK_INT >= 21) {
        total = count-1;
    }

Is why you dont see the option of the iptables, isnt a bug, is because the iptables isnt avalable in sdk >= 21


Jaime

**Comment by royalhacker** [comment]
is it due to pie 

and then how does evil mana works

**Comment by offensive-security** [comment]
Using ip policy routing...
