### ISSUE TITLE
Check for architecture fails on some 64 bit arm devices (such as samsung s5)

### ISSUE THREAD

**Issue by ecofriendly** [offensive-security/nethunter-app#46]
On the "fattire-rebased" branch, the variable "dir" is set to null instead of "arm" because of an incomplete check of arm64 devices.  As you can see [here](https://github.com/offensive-security/nethunter-app/blob/fattire-rebased/src/com/offsec/nethunter/ChrootManagerFragment.java#L145-L146), the architecture is expected to say "arm", which is true in most "arm64" devices.  However, some devices such as mine, the Samsung S5 say that they are "aarch64" instead, which fails the test.  The solution is to do a check for either "arm" or "aarch64"  by changing line 145 to this:

FROM:      if (ARCH.contains("arm")) {
TO:      if (ARCH.contains("arm") || ARCH.contains("aarch64")) {

Special thanks to @fat-tire who SO PATIENTLY walked me through installing Android Studio and teaching me how to use github's desktop app and everything so that I could build it on Windows. 

Be sure to follow him on twitter at @fat__tire. (you're welcome)

**Comment by fat-tire** [comment]
Oh shucks, you shouldn't have.

I guess arm64 was apple's version and aarch64 was everyone else in llvm, and they [merged](https://www.phoronix.com/scan.php?page=news_item&px=MTY5ODk) at some point.

Anyway, I think assuming it works now for ecofriendly that this is a good fix.

**Comment by binkybear** [comment]
Thanks @ecofriendly, I believe this should fix issue.
