### ISSUE TITLE
Errors in HIDFragment and DuckHunterFragment

### ISSUE THREAD

**Issue by mame82** [offensive-security/nethunter-app#47]
I've managed to compile a custom kernel for Samsung GT-I9300 which runs with CM-12.1 and nethunter (kali2  branch) rootfs. HID wasn't working, but running the scripts by hand does ("bootkali hid-cmd --de" for example).
The Problem could be brought down to missing exclamation marks. Changing

command[0] = "su -c bootkali hid-cmd --" + lang;

to

command[0] = "su -c \"bootkali hid-cmd --" + lang + "\"";

in HidFragment.java solves the problem. This comes true for all command[0] strings in HidFragment.java
and DuckHunterFragment.java.

Another problem in bringing duckhunter to work is the absence of /sdcard/files/modules/duckhunter.py - maybe I was missing something, building the rootfs, but it seems duckhunter.py isn't present in the git-repo of nethunter (neither master nor kali2 branch).

Could you be so Kind and fix the issue in the nethunter.apk delivered with the nethunter sources, because I'm not able to sign a release version of the recompiled apk.

BTW - I used eclipse to build the apk and have had problems  with the BuildConfig.* variables, which needed to be removed in order to make this Thing compile (eclipse seems to be ignoring build.gradle).

Additional question: Where is the "Start Webserver" Option which could be seen in the official offensive-security Videos - for remote activities it would be much better to use a web-based app than the apk

**Comment by binkybear** [comment]
Hi @mame82,

Thank you for the detailed report and suggested fixes.  It shouldn't be an issue fixing the hidfrag/duckfrag.  I'm pushing a patch right now if you want to try.

Duckhunter.py is grabbed during the build process: 
https://github.com/offensive-security/kali-nethunter/blob/master/androidmenu.sh#L875

I would highly suggest you use Android Studio instead of Eclipse.  Android has pretty much dropped support of Eclipse to support Android Studio and it has come a long way.  Combined with gradle it makes it pretty easy to get it up and running.  If you need help drop by IRC nethunter channel on freenode.

Start webserver was in the very first Nethunter before this app existed (I believe that was what you are referring to?).  It was considered not the safest/best solution so was removed in favor of the app.  

You can start webserver (apache) through app though if thats what you are talking about.

**Comment by mame82** [comment]
Hi @binkybear,
thank you for your fast reply. I'll try the patch next week and I think I'll take a closer look at Android Studio.

Considering duckhunter, something must have gone wrong during my rootfs build, cause some other files were  missing, too (maybe some wget's didn't run).

Yes, I refered to the web-app - surely it was difficult to maintain this - there must habe been mich editing of /etc/sudoers involved ;-) But I was looking for a solution to launch HID attacks from one nethunter device against a win7 host, triggered from a second nethunter device, which receives a reverse_vnc session from the host afterwards (routed through duckhunter in the first device). The Webapp would have been close to a one-click-solution, but the APK couldn't be controlled remotly. So I'll fall back to a ssh solution (starting bootkali by hand).

Let me ask one more question: why is the TERM env set to xterm-256color, jackpal.androidterm seems to work much better with screen-256color. I have also added a 'resize' to bashprofile, which helps alot switching between different Terminals.

I also added an additional option to bootkali which makes it able to run custom commands and carry them over to the chroot. Thus it could be used in custom scripts from outside the chroot (but maybe brings new security issues, we don't want in a production environment)

**Comment by mame82** [comment]
Hi @binkybear

The patches made are exactly the same I did before compiling and they work, thus I didn't synced the repo again to recompile (I'm running out of time finishing my project). Could you be so Kind and include the recompiled apk in "kali-nethunter". I opened another issue in kali-nethunter (#255) which needs to be fixed for keyseed.py in order to make duckhunter work (at least on dict_de keyboard layout).

**Comment by binkybear** [comment]
@mame82 - Just uploaded the new apk.  I'm going to close this issue since changes were made and new apk just got uploaded. 

Thanks for letting me know about problems, I do appreciate you finding these errors.  I will look into the dict_de issue  also.
