### ISSUE TITLE
Include win10 UAC in keyseed

### ISSUE THREAD

**Issue by jmingov** [offensive-security/nethunter-app#92]
https://github.com/offensive-security/nethunter-app/blob/master-2.1/assets/nh_files/modules/keyseed.py

Thanks  @sizzop for thouse keystrokes!

`win - "cmd" - right click (context menu) - down arrow - enter - left arrow - enter`

@binkybear ^^

**Comment by binkybear** [comment]
Maybe fixed in:

https://github.com/offensive-security/nethunter-app/commit/c591439c3e3fe7292e54839142521b12b7cc479c
