### ISSUE TITLE
"Error launching intent. Install Android Terminal!"

### ISSUE THREAD

**Issue by Gualty** [offensive-security/nethunter-app#98]
Hi,
today I installed all on my Nexus 5 (App, Chroot, etc...).

When I try to open something that need to be executed in a terminal a message appears: "Error launching intent. Install Android Terminal!"
I installed the "Android Terminal" app of Jack Malevich, the same app that was installed in previous version of Nethunter but the problem persists.

Anyone had the same issue?

Regards

**Comment by jmingov** [comment]
Not sure how you installed nethunter, we are using a cutom terminal now.

Is should be installed with the rest of the apps.

You can download it here: https://github.com/offensive-security/kali-nethunter/blob/master/AnyKernel2/data/app/Term-nh.apk

But looks like your install is not complete/ not well installed.

You created a installer with anykernel?

**Comment by Gualty** [comment]
I downloaded the app from GitHub and the compiled with Android Studio. But maybe it was not the right procedure...
I'm trying to install it

**Comment by jmingov** [comment]
Remove the chroot, remove the app, build the installer from:

https://github.com/offensive-security/kali-nethunter/tree/newinstaller-fj/AnyKernel2

Root the phone, install TWRP and flash the zip youll get from the installer.

If you can not build it yourself, use the stable release from: 

https://www.offensive-security.com/kali-linux-nethunter-download/

More info here:

https://github.com/offensive-security/kali-nethunter/wiki

Think that this repo is not the main one, is just a part of nethunter.

Im closing this, future issues should be opened in https://github.com/offensive-security/kali-nethunter 


Jaime

**Comment by bkr32** [comment]
Issue seems to be present on cos13
